### Write a function so that the columns of the output matrix are powers of the input vector.

In [1]:
import numpy as np

In [150]:
x = np.array([4,2,3,4,5])
n = 4
y = np.vander(x,n)
y

array([[ 64,  16,   4,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [158]:
def vander_matrix(x,n):
    s = np.arange(len(x)*n).reshape(len(x),n)
    for i in range(len(x)):
        for j in range(n):
            s[i][n-j-1]=x[i]**j
    print(s)

    
y = [4,2,3,4,5]
p=4   
    

In [159]:
vander_matrix(y,p)

[[ 64  16   4   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


In [165]:
n = 10
y = np.array([10,20,30,40,50,60,70,80,90,100])
k = 4
x = []

In [199]:
x=[]
def moving_average(y,k):
    n = len(y)
    for i in range(n-k+1):
        s = 0
        for j in range(k):
            s+=y[j+i]
        x.append(s/k) 
    return x
        
    

In [196]:
moving_average(y,k)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

In [200]:
y = [3,5,7,2,8,10,11,65,72,81,99,100,150]
k = 3
moving_average(y,k)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]

In [202]:
len(y)

13